/**
 * Build script for Ultra editor
 * 
 * Generates embedded config from JSON files and compiles the binary.
 */

import { $ } from "bun";
import * as fs from "fs";
import * as path from "path";

// Step 1: Generate defaults.ts from JSON config files
console.log("Generating embedded config from JSON files...");

const configDir = "./config";
const themesDir = path.join(configDir, "themes");
const outputFile = "./src/config/defaults.ts";

// Read JSON files
const keybindingsJson = fs.readFileSync(
  path.join(configDir, "default-keybindings.json"),
  "utf-8"
);
const settingsJson = fs.readFileSync(
  path.join(configDir, "default-settings.json"),
  "utf-8"
);

// Parse to validate and re-stringify for clean formatting
const keybindings = JSON.parse(keybindingsJson);
const settings = JSON.parse(settingsJson);

// Read all theme files
const themeFiles = fs.readdirSync(themesDir).filter(f => f.endsWith('.json'));
const themes: Record<string, any> = {};

for (const themeFile of themeFiles) {
  const themeName = themeFile.replace('.json', '');
  const themeJson = fs.readFileSync(path.join(themesDir, themeFile), "utf-8");
  themes[themeName] = JSON.parse(themeJson);
  console.log(`  Loaded theme: ${themeName}`);
}

// Generate TypeScript file
const generatedTs = `/**
 * Default Configuration (Auto-generated)
 * 
 * DO NOT EDIT THIS FILE DIRECTLY!
 * Edit the JSON files in config/ and run build to regenerate.
 * 
 * Generated from:
 *   - config/default-keybindings.json
 *   - config/default-settings.json
 *   - config/themes/*.json
 */

import type { KeyBinding } from '../input/keymap.ts';
import type { Theme } from '../ui/themes/theme-loader.ts';

export const defaultKeybindings: KeyBinding[] = ${JSON.stringify(keybindings, null, 2)};

export const defaultSettings: Record<string, any> = ${JSON.stringify(settings, null, 2)};

export const defaultThemes: Record<string, Theme> = ${JSON.stringify(themes, null, 2)};
`;

fs.writeFileSync(outputFile, generatedTs);
console.log(`Generated ${outputFile}`);

// Step 2: Patch typescript-language-server CLI for bundling
console.log("Patching typescript-language-server CLI...");
const tsServerVersion = '5.1.3';
const cliSource = fs.readFileSync('./node_modules/typescript-language-server/lib/cli.mjs', 'utf-8');
// Replace the package.json version read with a hardcoded version
const patchedCli = cliSource.replace(
  /const \{version: version\} = JSON\.parse\(readFileSync\(new URL\('\.\.\/package\.json', import\.meta\.url\), \{\s*encoding: 'utf8'\s*\}\)\);/,
  `const version = '${tsServerVersion}'; // PATCHED for bundling`
);
fs.writeFileSync('./src/lsp-servers/tsserver-cli.mjs', patchedCli);
console.log(`  Patched tsserver-cli.mjs (version ${tsServerVersion})`);

// Step 3: Compile the binaries
console.log("Compiling ultra binary...");
await $`bun build --compile --target=bun-darwin-arm64 ./src/index.ts --outfile ultra`;

// Step 4: Compile the bundled TypeScript language server
console.log("Compiling ultra-tsserver binary...");
await $`bun build --compile --target=bun-darwin-arm64 ./src/lsp-servers/tsserver-wrapper.ts --outfile ultra-tsserver`;

console.log("Build complete!");
