/**
 * Build script for Ultra editor
 *
 * Generates embedded config from JSONC files and compiles the binary.
 */

import { $ } from "bun";
import * as fs from "fs";
import * as path from "path";

/**
 * Strip comments from JSONC content
 */
function stripJsonComments(content: string): string {
  return content
    .replace(/\/\/.*$/gm, '') // Single line comments
    .replace(/\/\*[\s\S]*?\*\//g, ''); // Multi-line comments
}

/**
 * Read and parse a JSONC file
 */
function readJsonc(filePath: string): unknown {
  const content = fs.readFileSync(filePath, "utf-8");
  return JSON.parse(stripJsonComments(content));
}

// Step 1: Generate defaults.ts from JSONC config files
console.log("Generating embedded config from JSONC files...");

const configDir = "./config";
const themesDir = path.join(configDir, "themes");
const outputFile = "./src/config/defaults.ts";

// Read JSONC files (with comment support)
const keybindings = readJsonc(path.join(configDir, "default-keybindings.jsonc"));
const settings = readJsonc(path.join(configDir, "default-settings.jsonc"));

// Read BOOT.md
const bootMd = fs.readFileSync(
  path.join(configDir, "BOOT.md"),
  "utf-8"
);

// Read all theme files
const themeFiles = fs.readdirSync(themesDir).filter(f => f.endsWith('.json'));
const themes: Record<string, any> = {};

for (const themeFile of themeFiles) {
  const themeName = themeFile.replace('.json', '');
  const themeJson = fs.readFileSync(path.join(themesDir, themeFile), "utf-8");
  themes[themeName] = JSON.parse(themeJson);
  console.log(`  Loaded theme: ${themeName}`);
}

// Generate TypeScript file
const generatedTs = `/**
 * Default Configuration (Auto-generated)
 *
 * DO NOT EDIT THIS FILE DIRECTLY!
 * Edit the JSONC files in config/ and run build to regenerate.
 *
 * Generated from:
 *   - config/default-keybindings.jsonc
 *   - config/default-settings.jsonc
 *   - config/themes/*.json
 *   - config/BOOT.md
 */

import type { KeyBinding, Theme } from '../services/session/types.ts';

export const defaultKeybindings: KeyBinding[] = ${JSON.stringify(keybindings, null, 2)};

export const defaultSettings: Record<string, any> = ${JSON.stringify(settings, null, 2)};

export const defaultThemes: Record<string, Theme> = ${JSON.stringify(themes, null, 2)};

export const defaultBootFile: string = ${JSON.stringify(bootMd)};
`;

fs.writeFileSync(outputFile, generatedTs);
console.log(`Generated ${outputFile}`);

// Step 2: Compile the binary
console.log("Compiling ultra binary...");

// Auto-detect platform and architecture for cross-platform builds
const platform = process.platform; // 'darwin', 'linux', 'win32'
const arch = process.arch; // 'arm64', 'x64'
const bunPlatform = platform === 'win32' ? 'windows' : platform;
const target = `bun-${bunPlatform}-${arch}`;

console.log(`Building for target: ${target}`);

// Mark node-pty as external since it may not be installed (we fall back to bun-pty)
await $`bun build --compile --target=${target} --external node-pty ./src/index.ts --outfile ultra`;

console.log("Build complete!");
