/**
 * ANSI Utilities
 *
 * Consolidated ANSI escape sequence utilities for terminal rendering.
 */

// Sequences - cursor, screen, modes
export {
  CSI,
  OSC,
  ST,
  BEL,
  cursorUp,
  cursorDown,
  cursorForward,
  cursorBack,
  cursorNextLine,
  cursorPrevLine,
  cursorToColumn,
  cursorTo,
  cursorToZero,
  cursorHome,
  cursorSave,
  cursorRestore,
  cursorPositionRequest,
  cursorHide,
  cursorShow,
  cursorStyle,
  clearScreen,
  clearLine,
  clearScreenAndHome,
  scrollUp,
  scrollDown,
  setScrollRegion,
  resetScrollRegion,
  alternateScreenOn,
  alternateScreenOff,
  lineWrapOn,
  lineWrapOff,
  mouseTrackingOn,
  mouseTrackingOff,
  mouseButtonTrackingOn,
  mouseButtonTrackingOff,
  mouseAnyEventOn,
  mouseAnyEventOff,
  mouseSgrModeOn,
  mouseSgrModeOff,
  mouseFullOn,
  mouseFullOff,
  bracketedPasteOn,
  bracketedPasteOff,
  setTitle,
  requestTerminalSize,
  bell,
  softReset,
  hardReset,
  focusTrackingOn,
  focusTrackingOff,
} from './sequences.ts';

// Colors - color parsing and ANSI color sequences
export {
  NAMED_COLORS,
  hexToRgb,
  rgbToHex,
  parseColor,
  resetColor,
  defaultFg,
  defaultBg,
  fg24bit,
  bg24bit,
  fgRgb,
  bgRgb,
  fgColor,
  bgColor,
  fg256,
  bg256,
  lighten,
  darken,
  mix,
  luminance,
  contrastRatio,
  isDark,
  isLight,
  type RGB,
} from './colors.ts';

// Styles - text styling and cell rendering
export {
  bold,
  boldOff,
  dim,
  dimOff,
  italic,
  italicOff,
  underline,
  underlineOff,
  blink,
  blinkOff,
  inverse,
  inverseOff,
  hidden,
  hiddenOff,
  strikethrough,
  strikethroughOff,
  buildStyle,
  cellStyle,
  styled,
  diffCells,
  transitionStyle,
  stylesMatch,
  type StyleOptions,
  type StyleDiff,
} from './styles.ts';
